export const FETCH_CONTENT_REQUESTED = "FETCH_CONTENT_REQUESTED";
export const FETCH_CONTENT_PROCESSING = "FETCH_CONTENT_PROCESSING";
export const FETCH_CONTENT_SUCCEEDED = "FETCH_CONTENT_SUCCEEDED";
export const FETCH_CONTENT_FAILED = "FETCH_CONTENT_FAILED";
export const FETCH_CONTENT_RESET = "FETCH_CONTENT_RESET";

export const UPDATE_RECORD_DETAILS_REQUESTED =
  "UPDATE_RECORD_DETAILS_REQUESTED";
export const UPDATE_RECORD_DETAILS_PROCESSING =
  "UPDATE_RECORD_DETAILS_PROCESSING";
export const UPDATE_RECORD_DETAILS_SUCCEEDED =
  "UPDATE_RECORD_DETAILS_SUCCEEDED";
export const UPDATE_RECORD_DETAILS_FAILED = "UPDATE_RECORD_DETAILS_FAILED";
export const UPDATE_RECORD_DETAILS_RESET = "UPDATE_RECORD_DETAILS_RESET";

export const DELETE_RECORD_REQUESTED = "DELETE_RECORD_REQUESTED";
export const DELETE_RECORD_PROCESSING = "DELETE_RECORD_PROCESSING";
export const DELETE_RECORD_SUCCEEDED = "DELETE_RECORD_SUCCEEDED";
export const DELETE_RECORD_FAILED = "DELETE_RECORD_FAILED";
export const DELETE_RECORD_RESET = "DELETE_RECORD_RESET";
